{
 "title": "Project 2",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "App Start Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "application_started_time_seconds"
    }
   ]
  },
  {
   "title": "Disk Total Bytes",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "disk_total_bytes" }
   ]
  },
  {
   "title": "Application Restarts",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "changes(process_start_time_seconds {job=\"project2\"}[1h])"
    }
   ]
  },
  {
   "title": "System CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    { "expr": "system_cpu_usage" }
   ]
  },
  {
   "title": "Disk Free Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "disk_free_bytes" }
   ]
  },
  {
   "title": "JVM Recent CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "process_cpu_usage" }
   ]
  },
  {
   "title": "Login Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    { "expr": "login_fail_counter_total" },
    { "expr": "sum(login_time_seconds_count)" },
    {
     "expr": "sum(0.1*login_time_seconds_count)"
    }
   ]
  },
  {
   "title": "GET Request Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "getallitems_time_seconds_max" },
    { "expr": "getallusers_time_seconds_max" }
   ]
  },
  {
   "title": "POST Request Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    { "expr": "regsiter_time_seconds_max" },
    { "expr": "additem_time_seconds_max" }
   ]
  },
  {
   "title": "DELETE Request Execution Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    { "expr": "deleteitem_time_seconds_max" },
    { "expr": "deleteuser_time_seconds_max" }
   ]
  },
  {
   "title": "Logback Events",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    { "expr": "logback_events_total" }
   ]
  },
  {
   "title": "Log",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "{agent=\"promtail\"}"
    }
   ]
  }
 ]
}